First, please verify that the bug is not already filled:
https://github.com/PyCQA/pylint/issues/

Then create a new crash issue:
https://github.com/PyCQA/pylint/issues/new?assignees=&labels=crash%2Cneeds+triage&template=BUG-REPORT.yml


Issue title:
Crash ``[Errno 22] Invalid argument`` (if possible, be more specific about what made pylint crash)
Content:
When parsing the following file:

<!--
 If sharing the code is not an option, please state so,
 but providing only the stacktrace would still be helpful.
 -->

```python
import pandas as pd 
import numpy as np 
import datetime as dt
from datetime import timedelta
data = pd.read_csv(r'C:/Users/FarahmandZH/OneDrive - University of Twente/Documenten/PDEng Project/Data/BezettingFare.csv',
                    sep=';')

data['date'] = pd.to_datetime(data['IdDimDatum'].astype(str), format='%Y%m%d')

data['date'] = data.apply(
    lambda row: row['date'] + timedelta(1) if row['IdDimTijdBlok']>=24 else row['date'],
    axis=1)
# select only enschede lines 
enschede_lines = pd.read_csv(r'C:/Users/FarahmandZH/OneDrive - University of Twente/Documenten/PDEng Project/Data/Enschede_lines.csv',
                    sep=';') 

# enschede data 
enschede_data = pd.merge(data, enschede_lines, on=["IdDimLijnRichting", "IdDimLijnRichting"])

# bus stops 
bus_stops = pd.read_csv(r'C:/Users/FarahmandZH/OneDrive - University of Twente/Documenten/PDEng Project/Data/Twente_bus_stops.csv',
                    sep=';')
enschede_data = pd.merge(enschede_data, bus_stops, on=["IdDimHalte", "IdDimHalte"])

# remove unnecessary colums
enschede_data.drop(['IdFactBezetting', 'IdDimConcessie', 'IdDimModaliteit', 'Bron', 'RitVertrekTijdInt', 'PasseertijdInt', 'HalteVolgNr', 'IdDimOVChipHalte', 'Code_halte', 'Lengtegraad', 'Breedtegraad'], axis=1, inplace=True)


data.to_csv(r'C:/Users/FarahmandZH/OneDrive - University of Twente/Documenten/PDEng Project/Data/data_enschede.csv', sep=";")


```

pylint crashed with a ``OSError`` and with the following stacktrace:
```
Traceback (most recent call last):
  File "C:\Users\FarahmandZH\Anaconda3\envs\keolis\lib\site-packages\pylint\utils\ast_walker.py", line 73, in walk
    callback(astroid)
  File "C:\Users\FarahmandZH\Anaconda3\envs\keolis\lib\site-packages\pylint\checkers\variables.py", line 1722, in visit_import
    module = next(_infer_name_module(node, parts[0]))
  File "C:\Users\FarahmandZH\Anaconda3\envs\keolis\lib\site-packages\astroid\nodes\node_ng.py", line 182, in infer
    for i, result in enumerate(generator):
  File "C:\Users\FarahmandZH\Anaconda3\envs\keolis\lib\site-packages\astroid\decorators.py", line 136, in raise_if_nothing_inferred
    yield next(generator)
  File "C:\Users\FarahmandZH\Anaconda3\envs\keolis\lib\site-packages\astroid\decorators.py", line 105, in wrapped
    for res in _func(node, context, **kwargs):
  File "C:\Users\FarahmandZH\Anaconda3\envs\keolis\lib\site-packages\astroid\inference.py", line 266, in infer_import
    yield self.do_import_module(name)
  File "C:\Users\FarahmandZH\Anaconda3\envs\keolis\lib\site-packages\astroid\mixins.py", line 102, in do_import_module
    return mymodule.import_module(
  File "C:\Users\FarahmandZH\Anaconda3\envs\keolis\lib\site-packages\astroid\nodes\scoped_nodes\scoped_nodes.py", line 527, in import_module
    return AstroidManager().ast_from_module_name(absmodname)
  File "C:\Users\FarahmandZH\Anaconda3\envs\keolis\lib\site-packages\astroid\manager.py", line 189, in ast_from_module_name
    return self.ast_from_file(found_spec.location, modname, fallback=False)
  File "C:\Users\FarahmandZH\Anaconda3\envs\keolis\lib\site-packages\astroid\manager.py", line 102, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
  File "C:\Users\FarahmandZH\Anaconda3\envs\keolis\lib\site-packages\astroid\builder.py", line 134, in file_build
    return self._post_build(module, builder, encoding)
  File "C:\Users\FarahmandZH\Anaconda3\envs\keolis\lib\site-packages\astroid\builder.py", line 153, in _post_build
    self.add_from_names_to_locals(from_node)
  File "C:\Users\FarahmandZH\Anaconda3\envs\keolis\lib\site-packages\astroid\builder.py", line 209, in add_from_names_to_locals
    imported = node.do_import_module()
  File "C:\Users\FarahmandZH\Anaconda3\envs\keolis\lib\site-packages\astroid\mixins.py", line 102, in do_import_module
    return mymodule.import_module(
  File "C:\Users\FarahmandZH\Anaconda3\envs\keolis\lib\site-packages\astroid\nodes\scoped_nodes\scoped_nodes.py", line 527, in import_module
    return AstroidManager().ast_from_module_name(absmodname)
  File "C:\Users\FarahmandZH\Anaconda3\envs\keolis\lib\site-packages\astroid\manager.py", line 189, in ast_from_module_name
    return self.ast_from_file(found_spec.location, modname, fallback=False)
  File "C:\Users\FarahmandZH\Anaconda3\envs\keolis\lib\site-packages\astroid\manager.py", line 102, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
  File "C:\Users\FarahmandZH\Anaconda3\envs\keolis\lib\site-packages\astroid\builder.py", line 134, in file_build
    return self._post_build(module, builder, encoding)
  File "C:\Users\FarahmandZH\Anaconda3\envs\keolis\lib\site-packages\astroid\builder.py", line 153, in _post_build
    self.add_from_names_to_locals(from_node)
  File "C:\Users\FarahmandZH\Anaconda3\envs\keolis\lib\site-packages\astroid\builder.py", line 209, in add_from_names_to_locals
    imported = node.do_import_module()
  File "C:\Users\FarahmandZH\Anaconda3\envs\keolis\lib\site-packages\astroid\mixins.py", line 102, in do_import_module
    return mymodule.import_module(
  File "C:\Users\FarahmandZH\Anaconda3\envs\keolis\lib\site-packages\astroid\nodes\scoped_nodes\scoped_nodes.py", line 527, in import_module
    return AstroidManager().ast_from_module_name(absmodname)
  File "C:\Users\FarahmandZH\Anaconda3\envs\keolis\lib\site-packages\astroid\manager.py", line 189, in ast_from_module_name
    return self.ast_from_file(found_spec.location, modname, fallback=False)
  File "C:\Users\FarahmandZH\Anaconda3\envs\keolis\lib\site-packages\astroid\manager.py", line 102, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
  File "C:\Users\FarahmandZH\Anaconda3\envs\keolis\lib\site-packages\astroid\builder.py", line 134, in file_build
    return self._post_build(module, builder, encoding)
  File "C:\Users\FarahmandZH\Anaconda3\envs\keolis\lib\site-packages\astroid\builder.py", line 153, in _post_build
    self.add_from_names_to_locals(from_node)
  File "C:\Users\FarahmandZH\Anaconda3\envs\keolis\lib\site-packages\astroid\builder.py", line 209, in add_from_names_to_locals
    imported = node.do_import_module()
  File "C:\Users\FarahmandZH\Anaconda3\envs\keolis\lib\site-packages\astroid\mixins.py", line 102, in do_import_module
    return mymodule.import_module(
  File "C:\Users\FarahmandZH\Anaconda3\envs\keolis\lib\site-packages\astroid\nodes\scoped_nodes\scoped_nodes.py", line 527, in import_module
    return AstroidManager().ast_from_module_name(absmodname)
  File "C:\Users\FarahmandZH\Anaconda3\envs\keolis\lib\site-packages\astroid\manager.py", line 189, in ast_from_module_name
    return self.ast_from_file(found_spec.location, modname, fallback=False)
  File "C:\Users\FarahmandZH\Anaconda3\envs\keolis\lib\site-packages\astroid\manager.py", line 102, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
  File "C:\Users\FarahmandZH\Anaconda3\envs\keolis\lib\site-packages\astroid\builder.py", line 134, in file_build
    return self._post_build(module, builder, encoding)
  File "C:\Users\FarahmandZH\Anaconda3\envs\keolis\lib\site-packages\astroid\builder.py", line 160, in _post_build
    module = self._manager.visit_transforms(module)
  File "C:\Users\FarahmandZH\Anaconda3\envs\keolis\lib\site-packages\astroid\manager.py", line 79, in visit_transforms
    return self._transform.visit(node)
  File "C:\Users\FarahmandZH\Anaconda3\envs\keolis\lib\site-packages\astroid\transforms.py", line 88, in visit
    return self._visit(module)
  File "C:\Users\FarahmandZH\Anaconda3\envs\keolis\lib\site-packages\astroid\transforms.py", line 56, in _visit
    return self._transform(node)
  File "C:\Users\FarahmandZH\Anaconda3\envs\keolis\lib\site-packages\astroid\transforms.py", line 38, in _transform
    ret = transform_func(node)
  File "C:\Users\FarahmandZH\Anaconda3\envs\keolis\lib\site-packages\astroid\brain\helpers.py", line 10, in transform
    extension_module = get_extension_mod()
  File "C:\Users\FarahmandZH\Anaconda3\envs\keolis\lib\site-packages\astroid\brain\brain_numpy_core_numerictypes.py", line 105, in numpy_core_numerictypes_transform
    if numpy_supports_type_hints():
  File "C:\Users\FarahmandZH\Anaconda3\envs\keolis\lib\site-packages\astroid\brain\brain_numpy_utils.py", line 19, in numpy_supports_type_hints
    np_ver = _get_numpy_version()
  File "C:\Users\FarahmandZH\Anaconda3\envs\keolis\lib\site-packages\astroid\brain\brain_numpy_utils.py", line 29, in _get_numpy_version
    import numpy  # pylint: disable=import-outside-toplevel
  File "C:\Users\FarahmandZH\Anaconda3\envs\keolis\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import _distributor_init
  File "C:\Users\FarahmandZH\Anaconda3\envs\keolis\lib\site-packages\numpy\_distributor_init.py", line 26, in <module>
    WinDLL(os.path.abspath(filename))
  File "C:\Users\FarahmandZH\Anaconda3\envs\keolis\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 1455] The paging file is too small for this operation to complete

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\FarahmandZH\Anaconda3\envs\keolis\lib\site-packages\pylint\utils\ast_walker.py", line 76, in walk
    self.walk(child)
  File "C:\Users\FarahmandZH\Anaconda3\envs\keolis\lib\site-packages\pylint\utils\ast_walker.py", line 83, in walk
    traceback.print_exc()
  File "C:\Users\FarahmandZH\Anaconda3\envs\keolis\lib\traceback.py", line 179, in print_exc
    print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)
  File "C:\Users\FarahmandZH\Anaconda3\envs\keolis\lib\traceback.py", line 121, in print_exception
    print(line, file=file, end="")
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\FarahmandZH\Anaconda3\envs\keolis\lib\site-packages\pylint\lint\pylinter.py", line 1111, in _check_files
    self._check_file(get_ast, check_astroid_module, file)
  File "C:\Users\FarahmandZH\Anaconda3\envs\keolis\lib\site-packages\pylint\lint\pylinter.py", line 1146, in _check_file
    check_astroid_module(ast_node)
  File "C:\Users\FarahmandZH\Anaconda3\envs\keolis\lib\site-packages\pylint\lint\pylinter.py", line 1298, in check_astroid_module
    retval = self._check_astroid_module(
  File "C:\Users\FarahmandZH\Anaconda3\envs\keolis\lib\site-packages\pylint\lint\pylinter.py", line 1345, in _check_astroid_module
    walker.walk(node)
  File "C:\Users\FarahmandZH\Anaconda3\envs\keolis\lib\site-packages\pylint\utils\ast_walker.py", line 83, in walk
    traceback.print_exc()
  File "C:\Users\FarahmandZH\Anaconda3\envs\keolis\lib\traceback.py", line 179, in print_exc
    print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)
  File "C:\Users\FarahmandZH\Anaconda3\envs\keolis\lib\traceback.py", line 121, in print_exception
    print(line, file=file, end="")
OSError: [Errno 22] Invalid argument
```
